### PR TITLE
Akka.Monitoring.PerformanceCounters

### PR DESCRIPTION
**Pull request by MaciekLesiczka**

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
thanks for sending this in @MaciekLesiczka 

so at the moment there's no support for:

1. Gauges.
2. Timers.
3. Custom named counters. For instance, at the moment I couldn't track the number of restarts for a specific actor class?

**Comment by Aaronontheweb** [comment]
(Not criticizing the code, just want to be clear on what's been implemented and what will need to be filled in before we can release it.)

**Comment by MaciekLesiczka** [comment]
Actually, I've just implemented custom metrics, gauges and timers. Because performance counters need to be registered up-front, you need to provide metric names in ActorPerformanceCountersMonitor constructor, like in demo. Regarding counters,  everyone (built-in and custom) is handled by 2 types of performance counter - number of items, and rate per sec, so you can see, for instance how many restarts you had per sec, and total number of them.

**Comment by Aaronontheweb** [comment]
@MaciekLesiczka that's awesome!

> Because performance counters need to be registered up-front, you need to provide metric names in ActorPerformanceCountersMonitor constructor

Yeah, that's why I actually avoided using Performance counters for this and went with StatsD initially - but your solution for it works great.

One more request from you before I accept this - would you mind adding a little bit of content to the README that shows where these metrics will show up on Performance Monitor? Include some screenshots if possible (feel free to add an images folder.)  This will help make it easier for users to know where to look.

Also, join the Akka.NET gitter chat man - would love to have a contributor like you in there with us if you aren't already ;) https://gitter.im/akkadotnet/akka.net

**Comment by MaciekLesiczka** [comment]
@Aaronontheweb readme updated. I think we need nuget package for the assembly. I can add it to PR as well

**Comment by MaciekLesiczka** [comment]
>Also, join the Akka.NET gitter chat man - would love to have a contributor like you in there with us if you aren't already ;) https://gitter.im/akkadotnet/akka.net

Will do:)

**Comment by MaciekLesiczka** [comment]
@Aaronontheweb nuspec file added, please let me know if sth is still missing or need to be changed:)

**Comment by Aaronontheweb** [comment]
you did a fantastic job @MaciekLesiczka - thank you.

**Pull request merged**
