### PR TITLE
Akka.Monitoring.PerformanceCounters

### PR DESCRIPTION
**Pull request by MaciekLesiczka**
I've created monitoring implementation for performance counters. Used for my own project propuse, but I think it could be included here. At the moment it contains handlers for built-in counters with counting and rates/sec

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Hi @MaciekLesiczka - this looks awesome. Any reason why you closed the PR?

I also just realized that our build server didn't have the correct settings on and guests can't see the reasons why the build failed. Just fixed that a moment ago.

**Comment by MaciekLesiczka** [comment]
Hi Aaron,
Now I see the problem, thanks. I will reopen PR once the issue is fixed

**Comment by Aaronontheweb** [comment]
@MaciekLesiczka could you also send your PR into the `dev` branch instead? `master` branch will kick off a new NuGet release right away :p

**Comment by MaciekLesiczka** [comment]
got it:) added new PR

**Comment by Aaronontheweb** [comment]
Awesome! Now one last thing - I don't have a `contributing.md` doc for this repo yet but traditionally we follow this process for squashing commits as part of a pull request:

https://github.com/akkadotnet/akka.net/blob/dev/CONTRIBUTING.md

Essentially you'd need to squash your commits and then do a forced update to this branch. Would you mind doing that? It makes it easier to review all of the changes.

**Comment by MaciekLesiczka** [comment]
Hi Aaron, makes sense:) Commits squashed. Will try to follow all the rules next time:)

**Comment by Aaronontheweb** [comment]
Replacing this with #13

**Pull request closed without merging**
