### PR TITLE
added original statsd client and added an overload constructor to sta…

### PR DESCRIPTION
**Pull request by annymsMthd**
Added original NStatsD.Client nuget package.
Added overload for giving the monitor statsd server config.

### CODE REVIEW

**Comment by annymsMthd** [comment]
@Aaronontheweb need this for the yo project configuration. The new dnx stuff doesn't use app.configs

**Comment by Aaronontheweb** [comment]
The original NStatsD client had some major performance issues - have those been fixed?

**Comment by annymsMthd** [comment]
https://github.com/robbihun/NStatsD.Client/compare/master...Aaronontheweb:master
The only real difference I see now is the random number generator. If this is a big performance gain we should do a PR against their repo

**Comment by Aaronontheweb** [comment]
back in the day the issue was the async UdpClient.BeginSend - wrote a detailed blog post about it: http://www.aaronstannard.com/tradeoffs-in-high-performance-software/

**Comment by Aaronontheweb** [comment]
changing that method call to synchronous was a 40% throughput improvement

**Comment by Aaronontheweb** [comment]
(he'd probably accept a PR for it)

**Comment by annymsMthd** [comment]
Okay I can go ahead and send them a PR

**Comment by annymsMthd** [comment]
I'm not too impressed with the project. Should we try something like https://github.com/Pereingo/statsd-csharp-client? This guys actually has tests.

**Comment by annymsMthd** [comment]
@Aaronontheweb this has a breaking change in that you pass the monitor the statsd server configuration in the constructor, which is far better than a config section imo. The statsd client looks more mature and has test coverage.

**Comment by Aaronontheweb** [comment]
ok, I think we can still do a release of this but we'll need to bump the version #

**Comment by annymsMthd** [comment]
on it

**Comment by Aaronontheweb** [comment]
Sorry for the delay - let's merge this in and upgrade to Akka.NET v1.0.6 - deal?

**Pull request merged**
