### PR TITLE
Master

### PR DESCRIPTION
**Pull request by tomaszszczerba**
Hi,

Made two changes that I needed when using akka-monitoring.

1. when using ai for logging we don't need two places to configure client, thus new constructor that takes already configured instance/
2. TrackEvent creates a lot of noise in custom events and doesn't show in performance tracking, so I changed it for (proper in my opinion) TrackMetric.

Feel free to contact me if I missed something / did something wrong with pull request :) Thanks for great package and whole akka.net! :)

Regards,
Tomek.

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
Going to look into why this failed momentarily... weird...

**Comment by tomaszszczerba** [comment]
@Aaronontheweb did you get a chance to take a look at it? :)

**Comment by Aaronontheweb** [comment]
not yet - I'll give it a look now

**Comment by Aaronontheweb** [comment]
Restarting CI to see if it was an intermittent issue - runs fine locally.

**Comment by Aaronontheweb** [comment]
Yep, intermittent issue - runs fine now! Pushing out a new NuGet update with this.

**Comment by tomaszszczerba** [comment]
Thanks! :)

**Pull request merged**
